name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  QA_APP_NAME: stapp-vue2048-qa
  PROD_APP_NAME: stapp-vue2048-prod

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: corepack enable
      - run: pnpm config set store-dir .pnpm-store
      - run: pnpm install
      - uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  test:
    if: github.event_name == 'pull_request' # Exécuté seulement sur PR
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm type-check

  deploy-qa:
    needs: build
    if: github.event_name == 'workflow_dispatch' # Déploiement manuel seulement
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: https://${{ env.QA_APP_NAME }}.azurewebsites.net
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN_QA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"  
          api_location: ""    
          output_location: ""  

  deploy-prod:
    needs: build
    if: github.event_name == 'workflow_dispatch' # Déploiement manuel seulement
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.PROD_APP_NAME }}.azurewebsites.net
    steps:
      - uses: actions/download-artifact@v4 
        with:
          name: dist
          path: dist/
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"  
          api_location: ""    
          output_location: "" 
