stages:
  - build
  - qa
  - production
  - test

default:
  image: node:latest
  cache: &global_cache
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
      - node_modules/
    policy: pull
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-10 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install

build-package:
  stage: build
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - pnpm build
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
    - if :  $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  stage: test
  script:
    - pnpm lint
    - pnpm test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

deploy-qa:
  stage: qa
  environment:
    name: QA
  script:
    - pnpx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-qa --env=production
  rules : 
    - when: manual

deploy-production:
  stage: production
  environment:
    name: Prod
  script:
    - pnpx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-prod --env=production
  rules : 
    - when: manual
