name: CI/CD Pipeline

on:
  push:
    tags: 
      - 'v*' # match all tags starting with 'v'
    branches: [ main ]
    paths-ignore: 
      - 'docs/**'
  pull_request:
    types: [labeled, synchronize,closed]  
    branches: [ main ]
    paths-ignore: 
      - 'docs/**'
  workflow_dispatch:
      inputs:
        run_checks:
          description: 'Exécuter les analyses et tests'
          required: true
          type: boolean
          default: false
  schedule:
    - cron: '0 8 * * 1'
env:
  QA_APP_NAME: stapp-vue2048-qa
  PROD_APP_NAME: stapp-vue2048-prod
  ARTIFACT_RETENTION_DAYS: ${{ github.ref == 'refs/heads/main' && 7 || 1 }}


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: corepack enable
      - run: pnpm config set store-dir .pnpm-store
      - run: pnpm install
      - uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}


  test:
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_checks) }}
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm type-check

  deploy-qa:
    needs: build
    if: ${{github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: https://${{ env.QA_APP_NAME }}.azurewebsites.net
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN_QA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"  
          api_location: ""    
          output_location: ""  

  deploy-prod:
    needs: build
    if: ${{github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.PROD_APP_NAME }}.azurewebsites.net
    steps:
      - uses: actions/download-artifact@v4 
        with:
          name: dist
          path: dist/
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"  
          api_location: ""    
          output_location: "" 
  create-pr-environment:
    needs: [build]
    #match PRs with the label 'deploy-preview' and not closed
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy-preview') && github.event.action != 'closed'}}  
    runs-on: ubuntu-latest
    environment: pr-preview
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to PR Environment
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN_QA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: ""
          output_location: ""
  
      - name: Get deployment URL
        id: get_url
        run: |

          URL="https://pr-${{ github.event.number }}-${{ env.QA_APP_NAME }}.azurestaticapps.net"
          echo "PR_ENV_URL=$URL" >> $GITHUB_OUTPUT
  
  
  cleanup_pr_environment:
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed'}}
      runs-on: ubuntu-latest
      steps:
        - name: Delete PR Environment
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN_QA }}
            action: "close"


  create-release:
    if: ${{startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: dist/**
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}