name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  QA_APP_NAME: stapp-vue2048-qa
  PROD_APP_NAME: stapp-vue2048-prod

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: corepack enable
      - run: pnpm config set store-dir .pnpm-store
      - run: pnpm install
      - uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm lint
      - run: pnpm test

  deploy-qa:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: https://${{ env.QA_APP_NAME }}.azurewebsites.net
    steps:
      - uses: pnpm/action-setup@v4
      - uses: actions/download-artifact@v4

        with:
          name: dist
      - run: pnpm dlx @azure/static-web-apps-cli deploy ./dist --app-name ${{ env.QA_APP_NAME }} --env=production

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.PROD_APP_NAME }}.azurewebsites.net
    steps:
      - uses: pnpm/action-setup@v4
      - uses: actions/download-artifact@v4 
        with:
          name: dist
      - run: pnpm dlx @azure/static-web-apps-cli deploy ./dist --app-name ${{ env.PROD_APP_NAME }} --env=production
